### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by necolas** [orangemug/instantiable-fastdom#11]
Please could you cut a new release for the patch that removes lodash.

**Comment by orangemug** [comment]
Yeah sorry @matthew-andrews is the only one with npm perms (don't ask I was being lazy a while back... sorry)

@matthew-andrews can you please release to npm.

**Comment by matthew-andrews** [comment]
what's your npm username? @orangemug

**Comment by matthew-andrews** [comment]
also is this a patch release a minor release?

**Comment by necolas** [comment]
a patch release i believe

**Comment by orangemug** [comment]
Thanks to @matthew-andrews we have a v0.1.5 on npm
